name: Image compression workflow
on:
  push:
    paths:
      - 'assets/pet-image/*.jpg'
      - 'assets/pet-image/*.jpeg'
jobs:
  compress-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
    - name: Compress images
      run: |
        find assets/pet-image -type f \( -iname "*.jpg" -o -iname "*.jpeg" \) -print0 | xargs -0 -P8 -I {} convert {} -quality 80 {}
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit -am "Compress images" || true
        git push
